name: journal_core
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Core editor engine
  appflowy_editor: 4.0.0

  # State management
  provider: ^6.1.2

  # Utilities
  easy_debounce: ^2.0.0
  uuid: ^4.0.0
  intl: ^0.19.0

  # Optional (for modals, icons, etc.)
  flutter_hooks: ^0.20.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
    - family: Phosphor
      fonts:
        - asset: assets/fonts/Phosphor.ttf
    - family: Custom
      fonts:
        - asset: assets/fonts/Custom.ttf

  assets:
    - assets/fonts/
