name: journal_core
description: Core block-based editor functionality for Steadfast Journal.
version: 0.0.5
homepage: https://github.com/ebrammer/journal_core
repository: https://github.com/ebrammer/journal_core

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Core editor engine
  appflowy_editor: ^4.0.0

  # State management
  provider: ^6.1.2

  # Utilities
  easy_debounce: ^2.0.0
  uuid: ^4.0.0
  intl: ^0.19.0

  # Optional (for modals, icons, etc.)
  flutter_hooks: ^0.20.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
